CREATE DATABASE IF NOT EXISTS DEV_DB
  CHARACTER SET 'utf8';

USE DEV_DB;

CREATE TABLE `CHERCHEUR` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `domaine` ENUM("INFO", "MATH", "IHM", "DESIGHN", "AUTRE") DEFAULT NULL,
  -- -- -- -- --
  CONSTRAINT `pk_CHERCHEUR` PRIMARY KEY (`id`)
);

CREATE TABLE `PUBLICATION` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  -- -- -- -- --
  CONSTRAINT `pk_PUBLICATION` PRIMARY KEY (`id`)
);

CREATE TABLE `AUTEURS` (
  `id_publication` INT(10) UNSIGNED NOT NULL,
  `id_chercheur` INT(10) UNSIGNED NOT NULL,
  -- -- -- -- --
  CONSTRAINT `pk_AUTEURS`
    PRIMARY KEY (`id_publication`, `id_chercheur`),
  CONSTRAINT `fk_AUTEURS_PUBLICATION`
    FOREIGN KEY (`id_publication`)
    REFERENCES `PUBLICATION`(`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AUTEURS_CHERCHEUR`
    FOREIGN KEY (`id_chercheur`)
    REFERENCES `CHERCHEUR`(`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
